version: '3.8'

networks:
  backend:
    driver: bridge

services:

  keycloak:
    image: quay.io/keycloak/keycloak:26.4
    container_name: keycloak_auth
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command:
      - start-dev
      - --import-realm
    
    networks:
      - backend
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak-config/import:/opt/keycloak/data/import:ro,Z
      - keycloak_data:/opt/keycloak/data/

  postgres:
    image: postgres:18-alpine
    container_name: user_profile_db
    networks:
      - backend
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: pgadmin
      POSTGRES_DB: fastapi_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres-init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro,Z

  redis:
    image: redis:latest
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  prometheus:
    image: prom/prometheus
    container_name: prometheus_monitor
    networks:
      - backend
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro,Z
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana_dashboard
    networks:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      prometheus:
        condition: service_started
  2fa_middleware:
    build: .
    container_name: 2fa_middleware
    networks:
      - backend
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
    env_file:
      - .env
    entrypoint: ["wait-for-postgres.sh"]
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  pgdata:
  keycloak_data:
  grafana_data:
  redis_data: